In this repository you can find the code I used for my bachelors thesis. The
source of the code will be listed in the code file.

* Project Description

  For my thesis, I will compare the performance of four algorithms on OpenAI gym
  environments. The four algorithms are: DQN, extended DQN, fitness search based 
  Genetic Algorithm, and a novelty search based Genetic Algorithm.  The ultimate 
  goal is to draw conclusion about the difference in tactics of Greedy and 
  non-greedy algorithms in Reinforcement Learning and Evolutionary lgorithms.

* Files

  The algorithms themselves can be found in the main directory under their
  environment and algorithm name (e.g Cartpole_DQN).

  Their performance is measured for both the "training" process and their
  performance test in csv files (e.g Cartpole_DQN_train_scores.csv). The csv files can be found in the data directory.

  The plot_evaluation file contains code to plot the progress of the algorithm
  based on the csv files, and creates images stored in the img directory under
  their respective names (e.g Cartpole_DQN_train_scores_plot.csv).
  
* References

  The code used is from the following sources:
  - Cartpole DQN: https://github.com/siddharthkale97/CartPole-v1-DeepQ-AI/blob/master/DeepQcartpole.py
  - Cartpole DQN extended: https://github.com/siddharthkale97/CartPole-v1-DeepQ-AI/blob/master/DeepQcartpole.py
  - Cartpole GA: https://gist.github.com/DollarAkshay/55e50158a1259cb4ef5675a427bf1781
  - Cartpole NS: https://www.jetnew.io/posts/2020/11/novelty-search/
  - Lunar DQN: https://github.com/ranjitation/DQN-for-LunarLander
  - Lunar DQN extended: https://github.com/ranjitation/DQN-for-LunarLander
  - Lunar GA: https://gist.github.com/DollarAkshay/e6fe84fdf721db2731948e8461092e5a
  - Lunar NS: https://www.jetnew.io/posts/2020/11/novelty-search/
  
